export const AUTH_USER = 'auth_user';
export const UNAUTH_USER = 'unauth_user';
export const AUTH_ERROR = 'auth_error';

export const FETCH_POSTS_STATUS = 'FETCH_POSTS_STATUS';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const CLEAR_POSTS = 'CLEAR_POSTS';
export const FETCH_ARTICLE_POST_SUCCESS = 'FETCH_ARTICLE_POST_SUCCESS';
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';

export const FETCH_TITLES_STATUS = 'FETCH_TITLES_STATUS';
export const FETCH_TITLES_SUCCESS = 'FETCH_TITLES_SUCCESS';
export const FETCH_UP_TITLES_SUCCESS = 'FETCH_UP_TITLES_SUCCESS';
export const CLEAR_TITLES = 'CLEAR_TITLES';
export const FETCH_TITLE_SUCCESS = 'FETCH_TITLE_SUCCESS';
export const CHANGE_TITLES_QUERY = 'CHANGE_TITLES_QUERY';

export const FETCH_ACTORS_STATUS = 'FETCH_ACTORS_STATUS';
export const FETCH_ACTORS_SUCCESS = 'FETCH_ACTORS_SUCCESS';
export const FETCH_UP_ACTORS_SUCCESS = 'FETCH_UP_ACTORS_SUCCESS';
export const CLEAR_ACTORS = 'CLEAR_ACTORS';
export const FETCH_ACTOR_SUCCESS = 'FETCH_ACTOR_SUCCESS'; 
export const CHANGE_ACTORS_QUERY = 'CHANGE_ACTORS_QUERY';
