// Auth
export const CALL_AUTH_TOKEN = 'CALL_AUTH_TOKEN';
export const CALL_USER_SIGN_OUT = 'CALL_USER_SIGN_OUT';
export const CALL_USER_SIGN_IN = 'CALL_USER_SIGN_IN';
export const CALL_USER_SIGN_UP = 'CALL_USER_SIGN_UP';
export const AUTH_USER = 'AUTH_USER';
export const UNAUTH_USER = 'UNAUTH_USER';
export const AUTH_STATUS = 'AUTH_STATUS';
export const AUTH_ERROR = 'AUTH_ERROR';

// User
export const CALL_EDIT_USER = 'CALL_EDIT_USER';
export const CALL_LOAD_AVATAR = 'CALL_LOAD_AVATAR';
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';

// App
export const DEFINE_NIGHT_MODE = 'DEFINE_NIGHT_MODE';

// Posts
export const CALL_FETCH_POSTS = 'CALL_FETCH_POSTS';
export const FETCH_POSTS_STATUS = 'FETCH_POSTS_STATUS';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_UP_POSTS_SUCCESS = 'FETCH_UP_POSTS_SUCCESS';
export const FETCH_ARTICLE_POST_SUCCESS = 'FETCH_ARTICLE_POST_SUCCESS';
export const CALL_FETCH_POST = 'CALL_FETCH_POST';
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';
export const POST_COMMENT_SUCCESS = 'POST_COMMENT_SUCCESS';

// Titles
export const CALL_FETCH_TITLES = 'CALL_FETCH_TITLES';
export const CALL_SET_TITLE_RATING = 'CALL_SET_TITLE_RATING';
export const CALL_CHANGE_TITLES_QUERY = 'CALL_CHANGE_TITLES_QUERY';
export const FETCH_TITLES_STATUS = 'FETCH_TITLES_STATUS';
export const FETCH_TITLES_SUCCESS = 'FETCH_TITLES_SUCCESS';
export const FETCH_UP_TITLES_SUCCESS = 'FETCH_UP_TITLES_SUCCESS';
export const FETCH_TITLE_SUCCESS = 'FETCH_TITLE_SUCCESS';
export const CHANGE_TITLES_QUERY = 'CHANGE_TITLES_QUERY';

// Actors
export const CALL_FETCH_ACTORS = 'CALL_FETCH_ACTORS';
export const FETCH_ACTORS_STATUS = 'FETCH_ACTORS_STATUS';
export const FETCH_ACTORS_SUCCESS = 'FETCH_ACTORS_SUCCESS';
export const FETCH_UP_ACTORS_SUCCESS = 'FETCH_UP_ACTORS_SUCCESS';
export const CLEAR_ACTORS = 'CLEAR_ACTORS';
export const FETCH_ACTOR_SUCCESS = 'FETCH_ACTOR_SUCCESS';
export const CALL_CHANGE_ACTORS_QUERY = 'CALL_CHANGE_ACTORS_QUERY';
export const CHANGE_ACTORS_QUERY = 'CHANGE_ACTORS_QUERY';
export const LIKE_ACTOR_STATUS = 'LIKE_ACTOR_STATUS';
export const CALL_ACTOR_LIKE = 'CALL_ACTOR_LIKE';
export const SAVE_ACTOR_LIKE = 'SAVE_ACTOR_LIKE';
export const REMOVE_ACTOR_LIKE = 'REMOVE_ACTOR_LIKE';

export const FETCH_REVIEWS_STATUS = 'FETCH_REVIEWS_STATUS';
export const FETCH_REVIEWS_SUCCESS = 'FETCH_REVIEWS_SUCCESS';
export const FETCH_UP_REVIEWS_SUCCESS = 'FETCH_UP_REVIEWS_SUCCESS';
export const CLEAR_REVIEWS = 'CLEAR_REVIEWS';
export const FETCH_REVIEW_SUCCESS = 'FETCH_REVIEW_SUCCESS';
export const RATE_REVIEW_STATUS = 'RATE_REVIEW_STATUS';
